FROM nwilken/ci-build:latest
MAINTAINER Nate Wilken <wilken@asu.edu>

USER root

RUN apk add --no-cache openjdk8 apache-ant gnupg

ENV TOMCAT_MAJOR 8
ENV TOMCAT_VERSION 8.5.34
ENV TOMCAT_TGZ_URL https://www.apache.org/dist/tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz
ENV DBCP_VERSION 7.0.91
ENV DBCP_JAR https://repo1.maven.org/maven2/org/apache/tomcat/tomcat-dbcp/$DBCP_VERSION/tomcat-dbcp-$DBCP_VERSION.jar

RUN mkdir -p /usr/local/tomcat \
    && cd /usr/local/tomcat \
    && curl -sfSL "$TOMCAT_TGZ_URL" -o tomcat.tar.gz \
    && curl -sfSL "$TOMCAT_TGZ_URL.asc" -o tomcat.tar.gz.asc \
    && gpg --keyserver pgpkeys.mit.edu --recv-key 33C60243 \
    && gpg --verify tomcat.tar.gz.asc tomcat.tar.gz \
    && tar xf tomcat.tar.gz --strip-components=1 \
    && rm bin/*.bat \
    && rm tomcat.tar.gz* \
    && curl -sfSL "$DBCP_JAR" -o lib/tomcat-dbcp-$DBCP_VERSION.jar \
    && chown -R dev:dev /usr/local/tomcat

USER dev

ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
